name: Push to Google Apps Scripts
on: push

jobs:
  push:
    runs-on: ubuntu-latest

    steps:
      - name: Setup repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: "20"

      - name: Setup Clasp
        run: npm install -g @google/clasp

      - name: Push to AppsScripts
        run: cd apps-scripts-code/ && clasp push
